server:
  port: 8090
eureka:
  instance:
    #eureka 服务端的实例名称
    hostname: service-eureka
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是服务端，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://101.42.105.249:8090/eureka/
#      defaultZone: http://localhost:8090/eureka/
  dashboard:
    enabled: true
    path: /home
  server:
    #清除无效服务的定时任务，时间间隔。默认1分钟
    delta-retention-timer-interval-in-ms: 60000