server:
  port: 8000
#  修改编码类型为utf-8
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  application:
    name: service-department

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/