server:
  port: 4444

spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/
  instance:
    appname: zuul

zuul:
  routes:
    product:
      path: /product/**
      url: http://localhost:5555/