server:
  port: 4444

spring:
  application:
    name: service-zuul

zuul:
  routes:
    service-department:
      path: /department/**
      serviceId: service-department
      url: http://127.0.0.1:8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

ribbon:
  eureka:
    enabled: true